## Opprettesle av spesielle matriser

I matriseregning har vi noen ganger bruk for spesielle typer matriser. Matriser med et bestemt innhold. Årsaken til dette er at de har spesielle egenskaper.

numpy har egne funksjoner for å opprette disse.  

> Matrise med enere.  ```numpy.ones()```  
> Matrise med nullere.  ```numpy.zeros()```  
> Matrise med en fast verdi.  ```numpy.full()```  
> Identitetsmatrise.  ```numpy.identity()```  


De tre første gir matriser der alle elementer er lik: en, null eller en oppgitt verdi.  
For de tre første må man oppgi form/størrelse (shape).  
Skal matrisa være 1-dimensjonal setter man antall elementer i parentesen.  
Ønsker man en 2-dimensjonal matrise spesifiseres henholdsvis anall rader og kolonner som to verdier skilt med komma i en egen parentes.  

Identitetsmarisa er alltid kvadratisk. Der bruker man bare en verdi som parameter.  

De matrisene man får som resultat inneholder som standard flyttall. Hvis man vil at verdiene sial være heltall setter man komma etter størrelsen og skriver   ```dtype=int``` 

In [1]:
import numpy as np

np.ones(4)



array([1., 1., 1., 1.])

In [2]:
np.ones((4,3), dtype=int)



array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [3]:
np.zeros((4,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.full((3,4), 34)

array([[34, 34, 34, 34],
       [34, 34, 34, 34],
       [34, 34, 34, 34]])

#### Identitetsmatrise

Oppretter en kvadratisk array der det er 1 langs hoveddiagonalen mens de andre elementene er 0.  
Her trenger vi bare en verdi for å angi størrelsen.  
> Legg merke til at for identitetsmatrise gir størrelse n en n x n matrise mens for de andre vil den gi en 1 x n matrise.

In [5]:
np.identity(5)
#what type of array is this? float int or bool
#

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

For mer informasjon og flere rutiner for oppretting se:
https://numpy.org/doc/stable/reference/routines.array-creation.html