## Transponering av matriser

Transponering vil si å gjøre rader om til kolonner og kolonner om til rader.  
En annen måte å si det på er at man speiler matrisa om hoveddiagonalen.  
 
Dette er en operasjon som man ofte støter på i matriseregning og som derfor er nødvendig for å kunne jobbe med matriser via python.

numpy har to måter å gjøre dette på. Den ene er funksjonen ```transpose()``` og den andre er atributten ```.T```  
De gir i utgangspunktet samme resultat. Funksjonen har noen flere muligheter som vi ikke skal komme inn på.


In [1]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
y = x.T
print(y)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
z = np.transpose(y)
print(z)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Som vi ser får vi den opprinnelige array tilbake om man transponerer den to ganger.

I matematikken er det ofte nødvendig å transponere kolonne og radvektorer for å kunne gjøre de ønskede operasjoner. I python skilles det ikke på om en 1D-array er rad- eller kolonne-vektor og transponering har ingen virkning.  

In [4]:
y = np.array([1, 2, 3, 5])
z = y.T
print(z)

[1 2 3 5]
