## Matrisergning

For matriseregning skal vi bare se på multiplikasjon.

Produktet av to matriser er definert for to matriser av multiplikasjonskonforme størrelser. Det vil si at antall kolonner i a må være lik antall rader i b.  

Vi kan enten bruke operatoren ```@``` eller funksjonen ```numpy.matmul()``` for å utføre matrisemultiplikasjonen

In [2]:
import numpy as np

a = np.array([[2, 3, 2], [3, 2, 3]])
b = np.array([[3, 1, 3, 1], [1, 2, 1, 2], [2, 1, 2, 1]])
a @ b

array([[13, 10, 13, 10],
       [17, 10, 17, 10]])

Med litt spesielle verdier i matrisene blir resultatet også litt spesielt.

Produktet mellom en matrise og en passende identitetsmatrise er (den første) matrisa (uendret)

In [3]:
i3 = np.identity(3, dtype=int)
np.matmul(a, i3)

array([[2, 3, 2],
       [3, 2, 3]])

Produktet mellom en matrise og en passende matrise med bare enere gir en matrise der Alle elementene på hver rad er lik summen av elemetene på den raden i den første matrisa.

In [4]:
o3 = np.ones((3,3))
a @ o3

array([[7., 7., 7.],
       [8., 8., 8.]])