## NumPy og Arrays

NumPy er et tilleggsbibliiotek til Python. Det er lagen av Travis Oliphant og lansert i 2005.  
Det er et open source prosjekt og kan fritt benyttes.  

NumPy betyr Nummerisk Python.  

Et grunnleggende element i NumPy er ***array***. Det kan i mange tilfeller oversettes med tabell. Vi tenker kanskje på en array som en 1-dimensjonal (rad eler kolonne) med data og en tabell som en 2-dimensjonal ordning av data i rader og kolonner. Men den kan ha en, to eller flere dimensjoner. Faktisk kan den også være 0-dimensjonal. Har den bare ett element er den 0-dimensjonal.  

Vi bruker også begrepene vektor og matrise om henholdsvis 1D og 2D array.  

Ordet array vil på norsk ikke ha helt den samme betydning som på engelsk. Vi holder oss til den engelske betydningen. Ordet vektor brukes også om en 1-dimensjonal array. Det begrepet må ikke forveksles med vektor i geometri og fysikk.  

Før vi går videre må vi slå fast at et enkelt tall (en enkel verdi) kalles en skalar.

Her skal vi se på hvordan vi kan opprette arrays i NumPy.  

For dokumentasjon og mer informasjon om NumPy se:  
https://numpy.org/doc/stable/index.html  
https://www.w3schools.com/python/numpy/default.asp

### Array i forhold til List

Datatypen List i Python har noen egenskaper som gjør at vi kan klare å lage noe som kan brukes som en array med den. Men den er treg, mangler funksjonalitet og har noen egenskaper som gjør den mindre egnet.  

NumPy har mulighet til å lage et array-objekt som er mye bedre egnet til formålet.  
- Mye raskere. Mer effektiv
- Array i flere dimensjoner
- Funksjoner for å gjøre operasjoner på en array som en forventer
- Vektor og matriseoperajoner
- Matematiske funksjoner som kan operere på arrayen som helhet eller på alle element, enketvis

For at det skal være mer effektivt og å kunne utføre operasjonene trygt er det også noen restriksjoner.
- Elementene må være av samme type.
- Størrelsen er gitt under opprettelsen og kan ikke endres.
- Kan ikke legge til eller slette elementer.

I neste notatbok vil vi se hvordan vi kan komme rundt de to siste begrensningene.

### Opprette en Array

Når vi har importert NumPy kan vi bruke funksjonen array() der for å opprette en array. Det objektet som blir opprettet er av typen ***ndarray*** (numpy.ndarray).  


In [1]:
import numpy as np 

arrayEn = np.array([1, 2, 3, 4, 5])

print(arrayEn)

print(type(arrayEn))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Det vi her sender til funksjonen array() er en list(e) siden elementene står i hakeparenteser []. Vi kan også bruke tuple eller et annen array-lignende objekt.  
I resultatet ser vi at typen til den er numpy.ndarray. En annen måte å si det på er at vi har et numpy.ndarray-objekt.

Vi fikk en 1D array. Hvis det har noen betydning så ble dette en radvektor.  
For å lage en kolonnevektor må vi ha et ekstra sett med hakeparenteser og så kalle rutinen ```ndarray.T```  som transponerer, endrer aksene i arrayen.

In [2]:
import numpy as np 

arrayTo = np.array([[1, 2, 3]]).T

print(arrayTo)

[[1]
 [2]
 [3]]


I eksempelet over lagde vi en array med heltall. Men vi kan også buke flyttall, streng eller boolean.  

Hvis vi blander heltall og flyttall blir alle elementer flyttall.  
Hvis vi blander tall og strenger blir alle elementer strenger. 

In [3]:
arrayTo = np.array([1.5, 2.0, 3.14, 4.4, 5.7])
arrayTre = np.array(['Hei', 'på', 'deg'])
arrayFire = np.array([1, 2.2, 3, 4.4])
arrayFem = np.array([1, 2.2, 'tre'])

print(arrayTo)
print(arrayTre)
print(arrayFire)
print(arrayFem)

[1.5  2.   3.14 4.4  5.7 ]
['Hei' 'på' 'deg']
[1.  2.2 3.  4.4]
['1' '2.2' 'tre']


Foreløpig skal vi holde arrays med strenger litt utenfor og jobbe med arrays med tall.  

En array som har (flere) skalarer som element er 1-dimensjonal (1D) og er den mest vanlige standard array. Den kalles også for vektor, men det må ikke forveksles med vektorer i matematikken.  
Har arrayen bare en skalar som element er den 0-dimensjonal.  
En array kan også ha 1-dimensjonale array som element. Det blir da en 2-dimensjonal (2D) array.

In [4]:
# Eksempel på en enkel 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2d)

[[1 2 3]
 [4 5 6]]


En NumPy array kan ha enda flere dimensjoner, men det blir vi ikke å jobbe med i dette kurset.

### Sekvenser

I mange tilfeller trenger vi en bestemt sekvens med mange tall. For eksempel som x-verdier når vi skal regne ut y-verdier av en funksjon. Da kan det være fint med en enklere måte å lage denne sekvensen enn å skrive dem inn manuelt. Det er jo heller ikke sikkert at vi vet på forhånd hvordan denne sekvensen skal være, men at det er noe som blir beregnet underveis.  

NumPy har to funksjoner som forenkler opprettelsen av slike 1D arrays.  

#### np.arange

```numpy.arrange()```som oppretter en array med faste steg. Det spesifiseres ikke hvor mange elementer den skal inneholde. Den vanligste måten å bruke den på er med tre argumenter: ```numpy.arrange(start, stop, steg)```. 
> ***start*** er verdien arrayen skal starte på. Denne er med i arrayen.  
> ***stopp*** er verdien arrayen skal overskride. Denne er ikke med i arrayen.  
> ***steg*** er avstanden mellom hvert element.  

In [5]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

Det ble opprettet en array der elementene er heltall.  

Vi kan få en en array med elementer som er float ved å ta med en modifikator (dtype = float) som et ekstra argument.  
Vi får også elementer som er float dersom start eller steg er float.

In [6]:
np.arange(1, 10, 2, dtype = float)

array([1., 3., 5., 7., 9.])

In [7]:
np.arange(1.5, 6, 1)

array([1.5, 2.5, 3.5, 4.5, 5.5])

In [8]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

De kan kanskje være litt dumt at vi ikke får med 3. Det kan rettes på med å justere ***stopp***.

In [9]:
np.arange(2, 3.1, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. ])

Hvis vi bare har to argument blir steg satt til 1 som standard.

In [10]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

Og har vi bare ett element settes i tillegg start til 0.

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### numpy.linspace
```numpy.linspace()``` lager en array med et spesifisert antall elementer fra og med start til og med slutt. her får vi altså med begge endene. Den brukes slik: ```numpy.linspace(start, slutt, antall)```.  
> ***start*** er verdien arrayen skal starte på. Denne er med i arrayen.  
> ***slutt*** er verdien arrayen skal slutte på. Denne er med i arrayen.  
> ***antall*** er antall element i arrayen.  

```linspace()``` lager alltid elementer som er ```float```.

In [12]:
np.linspace(2, 10, 5)

array([ 2.,  4.,  6.,  8., 10.])

Her er altså både start og slutt med og vi får det anntall elementer som er spesifisert.

In [13]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

Hvis vi ikke tenker oss om kan vi få noen uforutsette resultat.  

Her ville kanskje i mange tilfeller vært bedre med:

In [14]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

NumPy har også funksjoner for å opprette spesielle 2D-arrays. Men det skal vi ikke komme innpå før vi skal jobbe med matriser.