## Arrays, grunnleggende bruk

Her skal vi se på hvordan vi helt grunnleggende håndterer arrays med NumPy. Så vil vi i senere moduler bruke det til konkrete anvendelser.

### Størrelse og indeksering

Det er ofte nødvendig å vite størrelsen på en array. Det vil si å vite hvor mange elementer som er i den. Til det gjør vi bruk av noen egenskapsvariabler til en array.  
> ```ndarray.size```    viser totalt antall elementer i arrayen  
> ```ndarray.shape```   viser hvor mange elementer det er langs hver dimensjon (akse)  

For en 1D array holder det å bruke size. For en 2D array vil size gi totalt antall elementer mens shape gir hvor mange rader og kolonner.

In [1]:
import numpy as np

arr1D = np.arange(3, 9.2, 0.5)

print(arr1D.size)

13


In [2]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2D.shape)

(2, 3)


Hele arrayen på en gang er vel og bra, men vi har ofte bruk for en enkelt element. For å få tilgang til et enkelt element utnytter vi at arrayen er ordnet og hvert element har en indeks.  

- Vi bruker hakeparenteser for å angi indeks.  
- Første element har indeks 0. Andre element har indeks 1. Og så videre.  
- Siste element har indeks som er en mindre enn antall elementer.  
- Hvis vi indekserer med en verdi som er lik antall elementer eller større får vi feilmelding.  
- Vi kan også indeksere bakfra med negative indekser.  
- Bakerste element har indeks -1. Nest bakerste element har indeks -2. Og så videre. 

In [3]:
print(arr1D)
print(arr1D[0])
print(arr1D[1])
print(arr1D[arr1D.size-1])
print(arr1D[-1])
print(arr1D[-2])

[3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9. ]
3.0
3.5
9.0
9.0
8.5


Skal vi angi et element i en 2D array må vi angi rad og kolonne som to tall adskilt med komma. Også her indekseres det fra 0.

In [4]:
print(arr2D[1, 2])

6


Man kan også angi en del av en array. Det kalles for slicing. Da angir man fra- og til-indeks adskilt med kolon. Fra-indeksen blir med, men ikke til_indeksen.

In [5]:
liten_del = arr1D[3:6]
stor_del = arr1D[1:-1]
print(liten_del)
print(stor_del)

[4.5 5.  5.5]
[3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5]


Man kan endre et element i en array på samme måten man endrer en vanlig variabel som inneholder en skalar. Man setter arrayen med indeks på venstresiden av likehetstegnet. Her er det viktig at man ikke indekserer utenfor arrayen.

In [6]:
arr1D[10]=12
print(arr1D)

[ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5 12.   8.5  9. ]


### Kopi av array

Når man tilordner en vanlig variabel som inneholder en skaler til en annen med ***=*** lager man en kopi som er uavhengig. Hva skjer når vi gjør det samme med en array?

In [7]:
arr2 = arr1D

arr2[3]=10

print(arr1D)

[ 3.   3.5  4.  10.   5.   5.5  6.   6.5  7.   7.5 12.   8.5  9. ]


Etter tilordning ble elemetet med indeks 3 for ***arr2*** endret. Når ***arr1D*** skrives ut ser vi, kanskje noe overraskende, at endringen er gjort for den også.  

Det skyldes at vi ikke har laget en kopi av selve arrayen. En array er et objekt som ligger lagret i minnet og «variabelen» er bare en referanse (henvisning) til selve arrayen. Tilordningen som ble gjort kopierte bare referansen. Vi har laget et alias til arrayen siden de viser til samme array.

Vi kan sjekke dette med funksjonen id() som gir en unik identifikator til et objekt.

In [8]:
print(id(arr1D))
print(id(arr2))

140476845522256
140476845522256


Det at tallene er like betyr at det er samme objekt.

For å lage en kopi av selve arrayen må vi bruke funksjonen ```objekt.copy()```. Her er det ikke numpy (eller np) som skal så foran punktum, men navnet på arrayen som skal kopieres. Vi bruker ingen argumenter i parentesen. Det går bra siden vi kaller den for den arrayen vi skal kopiere (setter navnet foran punktum). Funksjonen returnerer en array som er en eksakt kopi av den som står foran punktum.

In [9]:
arr3 = arr1D.copy()

print(id(arr1D))
print(id(arr3))

140476845522256
140476845519088


Her ser vi at ***arr1D*** og ***arr3*** har forskjellig id. De er forskjellige, uavhengige objekter. Men innholdet er likt, foreløpig.

### Legge til og fjerne elementer

Et array-objekt kan, som tidligere påpekt, ikke utvides eller innskrenkes. Men på samme måte som ```copy()``` lager et nytt array-objekt, har vi andre funksjoner som vi kan bruke for å lage en ny array med fler eller færre element enn den opprinnelige. Dette nye objektet kan så tilordnes den opprinnelige referansen. Da vil det i praksis være som om vi har lagt til eller fjærnet elementer i den opprinnelige arrayen.

For å legge til elementer i en array bruker vi funksjonen for array-sammenkobling ```numpy.concatenate()```. Den tar to, eller flere, array som argument. Det den gjør er å «koble sammen» arrayene som er argumenter i den rekkefølgen de står og returnerer en ny array.  
Legg merke til at det blir dobbel parentes i funksjonen.

In [10]:
arr_a = np.array([1, 2, 3, 4])
arr_b = np.array([5, 6, 7, 8])

arr_c = np.concatenate((arr_a, arr_b))
print(arr_c)

[1 2 3 4 5 6 7 8]


Når vi skal legge til elementer bruker vi samme funksjon. Vi lar det andre argumentet være den eller de element(ene) som skal legges til. Så tilordner vi den til samme navn som brukes som første argument.

In [11]:
arr1D = np.concatenate((arr1D, [4.5, 8]))
print(arr1D)

[ 3.   3.5  4.  10.   5.   5.5  6.   6.5  7.   7.5 12.   8.5  9.   4.5
  8. ]


Siden vi alltid føyer til på enden kan det være lurt å kjenne til sorteringsfunksjnen.

In [12]:
arr1D = np.sort(arr1D)
print(arr1D)

[ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.  10.
 12. ]


For å slette element bruker vi slicing. Er det fra en ende er det nok med den enkel slice.

In [13]:
arr1D = arr1D[0:-1]
print(arr1D)

[ 3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5  9.  10. ]


Skal vi slette et element inni, må vi bruke sammenkobling og to «slice».

In [14]:
arr1D = np.concatenate((arr1D[0:6], arr1D[7:14]))
print(arr1D)

[ 3.   3.5  4.   4.5  5.   5.5  6.5  7.   7.5  8.   8.5  9.  10. ]


Vi kan også snu rekkefølgen på elementene med ```numpy.flip()```.

In [15]:
print(np.flip(arr1D))

[10.   9.   8.5  8.   7.5  7.   6.5  5.5  5.   4.5  4.   3.5  3. ]


In [16]:
%whos

Variable    Type       Data/Info
--------------------------------
arr1D       ndarray    13: 13 elems, type `float64`, 104 bytes
arr2        ndarray    13: 13 elems, type `float64`, 104 bytes
arr2D       ndarray    2x3: 6 elems, type `int64`, 48 bytes
arr3        ndarray    13: 13 elems, type `float64`, 104 bytes
arr_a       ndarray    4: 4 elems, type `int64`, 32 bytes
arr_b       ndarray    4: 4 elems, type `int64`, 32 bytes
arr_c       ndarray    8: 8 elems, type `int64`, 64 bytes
liten_del   ndarray    3: 3 elems, type `float64`, 24 bytes
np          module     <module 'numpy' from '/us<...>kages/numpy/__init__.py'>
stor_del    ndarray    11: 11 elems, type `float64`, 88 bytes
