## Aritmetiske og nummeriske operasjoner på array

Noe av det fine med array i NumPy er at vi kan gjøre nummeriske operasjoner direkte på en array. En del av dem utfører operasjonene elementvis, mens andre jobber på hele arrayen.  

#### aritmetiske operatorer
Vi kan blant annet bruke de aritmetiske operatorene. Hvis vi bruker dem mellom en array og et tall (skalar) utføres operasjonen på hvert element.

In [1]:
import numpy as np

arr_a = np.array([1, 2, 3, 4])
arr_b = np.array([5, 6, 7, 8])

print(arr_a + 2)
print(arr_b - 1)
print(arr_a * 3)
print(arr_b / 2)

[3 4 5 6]
[4 5 6 7]
[ 3  6  9 12]
[2.5 3.  3.5 4. ]


Hvis vi bruker de arimetiske operatorene mellom to array, må vi passe på at de er like store. Operajonene utføres da elementvis. Det vil si først element i den ene med første element i den andre, andre element i den ene med andre element i den andre og så videre.

In [2]:
print(arr_a + arr_b)
print(arr_b - arr_a)
print(arr_a * arr_b)
print(arr_b / arr_a)

[ 6  8 10 12]
[4 4 4 4]
[ 5 12 21 32]
[5.         3.         2.33333333 2.        ]


Vi kan bruke dette til å regne ut funksjonsverdier. Hvis vi lager en array med x-verdiene kan vi lage y-verdiene ved å bruke arrayen som x i likningen.

In [3]:
x_verdi = np.arange(11)  # En array med heltallene fra 0 til 10
print(np.sqrt(x_verdi) ) # Skriver ut rota av tallene i x-verdi

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


Dette blir veldig kjekt når vi skal plotte grafer i neste modul.

#### Statistikk
Hvis arrayen inneholder et datasett kan vi gjøre enkel statistikk med funksjoner som hører til np.array.

In [4]:
datasett = np.array([[0.45, 0.17, 0.34, 0.55],
                     [0.54, 0.05, 0.40, 0.65],
                     [0.12, 0.82, 0.26, 0.57]])

summen = datasett.sum()
minst = datasett.min()
stoerst = datasett.max()
standardavvik = datasett.std()

print('sum:', summen, 'minste:', minst, 'største:', stoerst, 'standardavviket:', standardavvik)

sum: 4.920000000000001 minste: 0.05 største: 0.82 standardavviket: 0.22139707917374762
