In [5]:
!pip install numpy


     ---------------------------------------- 0.0/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     ------ --------------------------------- 10.2/59.7 kB ? eta -:--:--
     ------------- ------------------------ 20.5/59.7 kB 131.3 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/59.7 kB 163.8 kB/s eta 0:00:01
     -------------------------- ----------- 41.0/59.7 kB 178.6 kB/s eta 0:00:01
     -------------------------------------- 59.7/59.7 kB 211.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB 991.0 kB/s eta 0:00:13
   ---------------------------------------- 0.1/12.9 MB 1.7 MB/s eta 0:00:08
   - -------------------------------------- 0.3/12.9 MB 2.5 MB/s eta 0:00:05
   -- ------------------------------------- 0.6/12.9 MB 3.7 MB/s eta 0:00:04
   --- ------------------------------------ 1.1/12.9 MB 5.1 MB/s eta 0:00:03
   --


[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: C:\Users\julie\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [7]:
import numpy as np
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [8]:
np.linspace(0, 9, 9)

array([0.   , 1.125, 2.25 , 3.375, 4.5  , 5.625, 6.75 , 7.875, 9.   ])

In [9]:
np.linspace(0, 9, 7)

array([0. , 1.5, 3. , 4.5, 6. , 7.5, 9. ])

In [10]:
rekke1 = np.array([3, 5, 8, 21, 34])

In [11]:
rekke1[3]

np.int64(21)

In [12]:
rekke1[2]

np.int64(8)

In [13]:
rekke2 = np.array([7, 9, 13, 21,27])

In [15]:
rekke2[-2]

np.int64(21)

In [16]:
rekke2[3]

np.int64(21)

In [17]:
rekke3 = np.arange(1, 12, 1)

In [18]:
np.concatenate((rekke3[0:5], np.flip(rekke3[6:-1])))

array([ 1,  2,  3,  4,  5, 10,  9,  8,  7])

In [19]:
x = np.array([2, 3, 4, 5])
y = np.array([2, 6, 12, 15])


In [20]:
x**2


array([ 4,  9, 16, 25])

In [21]:
x+y

array([ 4,  9, 16, 20])

: 