In [1]:
import numpy as np


In [2]:
x = np.array([1,3,5])

In [3]:
x+2


array([3, 5, 7])

In [4]:
x*2


array([ 2,  6, 10])

In [5]:
y= np.array([2, 4, 6])

In [6]:
x+y

array([ 3,  7, 11])

In [7]:
np.sqrt(x)

array([1.        , 1.73205081, 2.23606798])

In [12]:
np.arange(0, 10.2, .5)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

: 