Når man skal løse lineære likningssett, hvor mange elementer blir det i koeffisientmatrisa? 

Vi har koeffisientmatrisa A og konstantmatrisa B som til sammen representerer et lineært ligningssett. Hvilken operasjonen brukes for å løse det lineære likningssettet?

In [1]:
import numpy as np

In [2]:
A = np.array([[2, 1, -1], # koeffisientmatrisen
              [-3, -1, 2],
              [-2, 1, 2]])

B = np.array([8, -11, -3]) #konstantmatrisen

In [3]:
np.linalg.solve(A, B) #løser likningssystemet

array([ 2.,  3., -1.])

Hvis vektoren P6 = [2 -1 -2 5] representer et polynom, hvilken grad har polynomet 

In [12]:
from numpy import array
import numpy.polynomial.polynomial as poly

In [19]:
Funksjonen polyroots() brukt på en vektor som representerer et polynom gir 

SyntaxError: invalid syntax (3717145392.py, line 1)

In [14]:
P7 = [2, -1, -2, 5]

In [18]:
np.roots(P7) #løser polynomet

array([-1.42745793+0.j        ,  0.96372896+0.90696835j,
        0.96372896-0.90696835j])

Vi kjører kommandoen:
polyint(P7)
der P7 er en vektor som representerer ett polynom. 
Første elementet i resultatvektoren 

In [15]:
np.polyint(P7) #integrasjon av polynom

array([ 0.5       , -0.33333333, -1.        ,  5.        ,  0.        ])