In [1]:
import numpy as np

In [2]:
tabell = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
tabell[2,1]

np.int64(8)

In [3]:
tabell = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
tabell[1]

array([4, 5, 6])

In [9]:
tabell = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
tabell[:, x]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
tabell = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
tabell[0,1] = 0
tabell

array([[1, 0, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
tabell = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
tabell[2,3] = 4

IndexError: index 3 is out of bounds for axis 1 with size 3

In [12]:
tabell = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
tab2 = np.array([[11, 12, 13], [14, 15, 16], [17, 18, 19]])
np.concatenate((tabell, tab2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])